version: '3.8'

services:
  database-mysql:
    build: .
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_DATABASE=ecommerce
      - MYSQL_ROOT_PASSWORD=Duyngo123@
    ports:
      - '3307:3306'
    expose:
      - 3306
  backend:
    build:
      context: ../BE
      dockerfile: Dockerfile
    restart: unless-stopped
    environment:
      - DB_PORT=3307
      - DB_HOST=database-mysql
      - DB_DATABASE_NAME=ecommerce
      - DB_USERNAME=root
      - DB_PASSWORD=Duyngo123@
      # - DB_HOST=host.docker.internal
    ports:
      - 8080:8080
    expose:
      - 8080
  nginx:
    image: nginx:latest
    build:
      context: ../FE
      dockerfile: Dockerfile
    ports:
      - 80:80
    volumes:
      - ./../FE/build:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - backend
